### ISSUE TITLE
Failed to activate the dusk-syntax theme

### ISSUE THREAD

**Issue by petaren** [jamesejr/dusk-syntax#2]
[Enter steps to reproduce below:]
1. Open settings
2. Search for dusk
3. Click install

**Atom Version**: 1.0.19
**System**: Mac OS X 10.11
**Thrown From**: [dusk-syntax](https://github.com/jamesejr/dusk-syntax) package, v1.0.1
### Stack Trace

Failed to activate the dusk-syntax theme

```
At 'base.less' wasn't found in /Users/petar/.atom/packages/dusk-syntax/index.less:1:0

LessError: 'base.less' wasn't found
  at /Users/petar/.atom/packages/dusk-syntax/index.less:1:0
```
### Commands

```
     -4:45.9.0 settings-view:open (atom-text-editor.editor.is-focused)
     -4:29.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
 28x -4:26.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -4:19.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
 10x -3:46.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -3:44.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
 17x -0:25.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:23.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
atom-text-transformer, v0.7.0
code-links, v0.3.11
highlight-line, v0.11.0
set-syntax, v0.3.0

# Dev
No dev packages
```

**Comment by jamesejr** [comment]
Thanks for reporting this, @petaren - I'll take a look into it.

**Comment by petaren** [comment]
You're welcome! I'm a big fan of the Dusk theme in Xcode and would love to use this theme in Atom as well! would greatly appreciate it if it could be fixed!

**Comment by jamesejr** [comment]
@petaren I'm running the same version of Atom, dusk-syntax, and Mac OS X. However, I'm unable to reproduce this problem. I tried uninstalling the package and reinstalling it, but it still works as intended without any issues that I could reproduce. The error appears to complain about a missing `base.less` file, however, it does exist in the package. I can keep poking around, but I haven't been successful at reproducing this problem. I'm sure you've tried this already, but have you tried reinstalling the package?

**Comment by petaren** [comment]
@jamesejr I know that I did try installing it back and forth. But I just tried installing it again and it seemed to work perfectly! 

Thank you for trying to figure it out nonetheless!
