### ISSUE TITLE
Deprecated selectors

### ISSUE THREAD

**Issue by kyleloyka** [jamesejr/dusk-syntax#3]
> Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors ...

Atom lists all the selectors that need to be modified (and what they should be changed to), but the list is quite long so I didn't post.

**Comment by jamesejr** [comment]
Thanks @kyleloyka I'll work on a fix as soon as possible and push up an update.
